In [24]:
import pyepicollect as pyep
import pprint
pp = pprint.PrettyPrinter(indent=2)
import pandas as pd
from pyproj import Transformer

In [2]:
CLIENT_ID = 6334
CLIENT_SECRET = 'QjnENZMPUSbOgVULeUBsCKNakJYrbbb2RJK07Hbn'
NAME = 'Bustard Field Observations V1'
SLUG = 'bustard-field-observations-v1'

In [3]:
result = pyep.api.search_project(NAME)
result

{'data': [{'type': 'project',
   'id': 'c248a1f437db470bb90ee9b7f08455c5',
   'project': {'name': 'Bustard Field Observations V1',
    'slug': 'bustard-field-observations-v1',
    'access': 'public',
    'ref': 'c248a1f437db470bb90ee9b7f08455c5'}}]}

In [5]:
token = pyep.auth.request_token(CLIENT_ID, CLIENT_SECRET)
pp.pprint(token)

{ 'access_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI2MzM0IiwianRpIjoiYTI2MWIxNTc3NjY1ZTViOWJlZDE1MDUzMzE0MzBmNGIwOGU2MjY0Njc3ODhjYzM0YzY3ZmQyYzY0MDEwOWY0ZTBkODYyYzk3NzY0N2I0N2IiLCJpYXQiOjE3NTIxMzMxMDUuOTE3Njk2LCJuYmYiOjE3NTIxMzMxMDUuOTE3NywiZXhwIjoxNzUyMTQwMzA1LjkxMjYzNywic3ViIjoiIiwic2NvcGVzIjpbXX0.qnSp9BNVcdSSQAWkhaivZFtRnoRN8iLFAqD2egKyX8cwdJHyscsr29yiK4IdhOwP0wZf0VXvwQ6hUIyezJqvxvhFK0K6hAgnv00s87DcODJ6j7bzkWLh0MnRUFk4CbjMZSevWnpRTimyh9jBcZA-deZ5WIsZQhNR9_Ll16mJMV9WNM__lSpK06j32AmWG63eckvaOEQpb_3zgp6BMV6nYF53tzRUsOvAZnB7QxuK2idmCJkzE2n5T2qJbVDmkWHLvg2iiKnhivnpegHiIvmrxFwGTxPxo10RnuvdEh2lbXBqobvqSk9tKC8TJERToLrppR66iAEyueQL11Gr17jrj6mtRJ6cmbDUnx20CPPTrISFNyxWS8ok4c1XTB00Pu1a0KhVox1S1ooBpMqrh9VEVoy1Oy1ab8j5seiB3thWiv4whJwD8mBgBHNDPeoorX_7Z-bpgXgfIsvASBjT1seKroBlhM81EbY_VxNK89x4RoXhffkCtdTrDy-xOaoRDDRvZ45aSaBguX69tbAPVuBgYHyjeYCLLGnuSa3Z5eIVF1gDQig97iwSIK2fqk584hvNDHLs9y_a1dec5gzYJIYusFWCiP5ScwdCSvT4Zzbk3CHrMTmaGe5R0H_075dLFK8OpK6cmbKeBgMHkEqT5HJaVTt5JWkLpcXeFXyXLzfLWu0',
  'expires_in': 7200,
  'token_type': 'Bearer'}

In [6]:
project = pyep.api.get_project(SLUG, token['access_token'])

In [7]:
entries = pyep.api.get_entries(SLUG, token['access_token'])
df_form= pd.DataFrame(entries['data']['entries'])

branch = pyep.api.get_branch_entries(SLUG, 'c248a1f437db470bb90ee9b7f08455c5_601e9130c790a_601e92ce97a99')
df_branch = pd.DataFrame(branch["data"]["entries"])

In [11]:
from datetime import date, timedelta

date_e = date.today()
date_s = date_e - timedelta(days=10)

In [12]:
df_form["3_Date"] = pd.to_datetime(df_form["3_Date"], dayfirst=True)
# Filter rows where the date is within the last 7 days
df_lastweek = df_form[df_form["3_Date"].dt.date >= date_s]

# Display the filtered results
print(df_lastweek)

                               ec5_uuid                created_at  \
0  ea9b3d79-5c25-46c0-b05d-796f849e468a  2025-07-02T11:44:51.000Z
1  79cf1f1f-8c0e-4ac3-8878-ad327bcdf82d  2025-07-01T11:57:58.000Z
2  1e553c5d-8748-482a-9bae-853993d4ec76  2025-06-30T13:30:25.000Z
3  fec40bde-45b1-4ae1-86eb-5434f2df33b9  2025-06-30T01:55:46.000Z

                uploaded_at                           title  \
0  2025-07-02T13:38:40.000Z  Pradhyuman 02/07/2025 17:14:27
1  2025-07-01T13:40:27.000Z  Pradhyuman 01/07/2025 17:05:44
2  2025-06-30T13:30:35.000Z  Pradhyuman 30/06/2025 18:57:19
3  2025-06-30T02:46:17.000Z  Pradhyuman 30/06/2025 07:11:28

  2_Name_of_the_person     3_Date 4_Start_Time 5_Type_of_survey  \
0         [Pradhyuman] 2025-07-02     17:14:27          Vehicle
1         [Pradhyuman] 2025-07-01     17:05:44          Vehicle
2         [Pradhyuman] 2025-06-30     18:57:19          Vehicle
3         [Pradhyuman] 2025-06-30     07:11:28          Vehicle

   6_Add_GIB_sighting  28_Flight 34_End_time 35_Areas_covered  \
0                   1          0    19:07:39    [Ramdevra EF]
1                   0          0    19:09:43    [Ramdevra EF]
2                   1          0    19:00:02    [Ramdevra EF]
3                   1          0    08:13:33   [Ramdevra ABC]

   36_Total_Kms_covered 37_Capparis_Flowerin  \
0                  11.0                  Yes
1                  14.0                  Yes
2                   9.0                  Yes
3                  11.0                  Yes

                           38_Fruiting_Trees                 39_Notes
0  [Pilu / Jaad / Jaal / Salvadora oleoides]
1  [Pilu / Jaad / Jaal / Salvadora oleoides]
2  [Pilu / Jaad / Jaal / Salvadora oleoides]
3  [Pilu / Jaad / Jaal / Salvadora oleoides]  3 Dogs inside Enclosure

In [37]:
# Ensure the key columns are named consistently
df_branch = df_branch.rename(columns={"ec5_branch_owner_uuid": "ec5_uuid"})

# Perform the left join
df = df_lastweek.merge(df_branch, on="ec5_uuid", how="left")

df = df[[
    "3_Date", "4_Start_Time", "5_Type_of_survey", "2_Name_of_the_person",
    "8_Species", "13_No_of_adult_males", "14_No_of_adult_femal",
    "15_No_of_immature_fe", "16_No_of_immature_ma", "17_No_of_unknown_age",
    "18_Notes", "20_Location", "21_Distance_from_obs", "22_Angle",
    "34_End_time", '35_Areas_covered','36_Total_Kms_covered'
]]


# Ensure time columns are in datetime format
df["4_Start_Time"] = pd.to_datetime(df["4_Start_Time"], errors="coerce")
df["34_End_time"] = pd.to_datetime(df["34_End_time"], errors="coerce")

# Calculate time spent in minutes
df["time_spent"] = ((df["34_End_time"] - df["4_Start_Time"]).dt.total_seconds() / 60).round(2)

# Ensure numeric columns are correct
df["13_No_of_adult_males"] = pd.to_numeric(df["13_No_of_adult_males"], errors="coerce")
df["14_No_of_adult_femal"] = pd.to_numeric(df["14_No_of_adult_femal"], errors="coerce")
df["15_No_of_immature_fe"] = pd.to_numeric(df["15_No_of_immature_fe"], errors="coerce")
df["16_No_of_immature_ma"] = pd.to_numeric(df["16_No_of_immature_ma"], errors="coerce")
df["17_No_of_unknown_age"] = pd.to_numeric(df["17_No_of_unknown_age"], errors="coerce")
df["36_Total_Kms_covered"] = pd.to_numeric(df["36_Total_Kms_covered"], errors="coerce")

# Add a column for period of day
df["survey_period"] = df["4_Start_Time"].dt.hour.apply(lambda x: "Morning" if x < 12 else "Evening")

# Main summary: include survey_period in groupby
df_summary = df.groupby(["3_Date", "survey_period"]).agg({
    "2_Name_of_the_person": lambda x: ", ".join(sorted(set(
        name for sublist in x for name in (sublist if isinstance(sublist, list) else [sublist])
    ))),
    "35_Areas_covered": lambda x: ", ".join(sorted(set(
        name for sublist in x for name in (sublist if isinstance(sublist, list) else [sublist])
    ))),
    "14_No_of_adult_femal": "sum",
    "13_No_of_adult_males": "sum",
    "15_No_of_immature_fe": "sum",
    "16_No_of_immature_ma": "sum",
    "17_No_of_unknown_age": "sum",
    "36_Total_Kms_covered": "sum"
}).reset_index()

# Add bird totals
df_summary["Immature_birds"] = (
    df_summary["15_No_of_immature_fe"] +
    df_summary["16_No_of_immature_ma"] +
    df_summary["17_No_of_unknown_age"]
)
df_summary["Total_birds"] = (
    df_summary["14_No_of_adult_femal"] +
    df_summary["13_No_of_adult_males"] +
    df_summary["Immature_birds"]
)

count_cols = ["Total_birds","Immature_birds",
    "14_No_of_adult_femal", "13_No_of_adult_males",
    "15_No_of_immature_fe", "16_No_of_immature_ma", "17_No_of_unknown_age"
]

df_summary[count_cols] = df_summary[count_cols].fillna(0).astype(int)

# Summarize time spent by date, period, and survey type
time_by_type = df.groupby(["3_Date", "survey_period", "5_Type_of_survey"])["time_spent"].sum().unstack(fill_value=0).reset_index()

# Ensure columns name is clean
time_by_type.columns.name = None

# Add missing columns if not present
if "Vantage" not in time_by_type.columns:
    time_by_type["Vantage"] = 0

if "Vehicle" not in time_by_type.columns:
    time_by_type["Vehicle"] = 0

# Rename for clarity
time_by_type = time_by_type.rename(columns={
    "3_Date": "3_Date",
    "Vantage": "Time_Spent_Vantage",
    "Vehicle": "Time_Spent_Vehicle"
})

# Merge
df_summary = df_summary.merge(time_by_type, on=["3_Date", "survey_period"], how="left")

# Rename and reorder columns
df_summary = df_summary.rename(columns={
    "3_Date": "Date",
    "35_Areas_covered": "Areas covered",
    "2_Name_of_the_person": "Observers",
    "14_No_of_adult_femal": "Females",
    "13_No_of_adult_males": "Males",
    "36_Total_Kms_covered": "Total_Km_Surveyed",
    "survey_period": "Period"
})

df_summary = df_summary[[
    "Date", "Period", "Areas covered","Observers", "Total_birds", "Females", "Males",
    "Immature_birds", "Time_Spent_Vantage", "Time_Spent_Vehicle", "Total_Km_Surveyed"
]]

df_summary_html=df_summary.to_html()

C:\Users\campa\AppData\Local\Temp\ipykernel_12452\1400576661.py:17: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["4_Start_Time"] = pd.to_datetime(df["4_Start_Time"], errors="coerce")
C:\Users\campa\AppData\Local\Temp\ipykernel_12452\1400576661.py:18: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["34_End_time"] = pd.to_datetime(df["34_End_time"], errors="coerce")

In [38]:
df_summary

,Date,Period,Areas covered,Observers,Total_birds,Females,Males,Immature_birds,Time_Spent_Vantage,Time_Spent_Vehicle,Total_Km_Surveyed
0,2025-06-30,Evening,Ramdevra EF,Pradhyuman,2,1,0,1,0,2.72,9.0
1,2025-06-30,Morning,Ramdevra ABC,Pradhyuman,1,0,1,0,0,62.08,11.0
2,2025-07-01,Evening,Ramdevra EF,Pradhyuman,0,0,0,0,0,123.98,14.0
3,2025-07-02,Evening,Ramdevra EF,Pradhyuman,2,1,0,1,0,113.20,11.0

In [28]:
import numpy as np
import pandas as pd
from pyproj import Proj, Transformer

# Extract fields from 20_Location dict
df["latitude"] = df["20_Location"].apply(lambda loc: loc.get("latitude") if isinstance(loc, dict) else None)
df["longitude"] = df["20_Location"].apply(lambda loc: loc.get("longitude") if isinstance(loc, dict) else None)
df["UTM_Easting"] = df["20_Location"].apply(lambda loc: loc.get("UTM_Easting") if isinstance(loc, dict) else None)
df["UTM_Northing"] = df["20_Location"].apply(lambda loc: loc.get("UTM_Northing") if isinstance(loc, dict) else None)
df["UTM_Zone"] = df["20_Location"].apply(lambda loc: loc.get("UTM_Zone") if isinstance(loc, dict) else None)

# Create df_locations with relevant fields
df_locations = df[[
    "3_Date", "4_Start_Time", "5_Type_of_survey", "2_Name_of_the_person",
    "8_Species", "13_No_of_adult_males", "14_No_of_adult_femal",
    "15_No_of_immature_fe", "16_No_of_immature_ma", "17_No_of_unknown_age",
    "latitude", "longitude", "UTM_Easting", "UTM_Northing", "UTM_Zone"
]].copy()

# Ensure necessary columns are numeric
df["UTM_Easting"] = pd.to_numeric(df["UTM_Easting"], errors="coerce")
df["UTM_Northing"] = pd.to_numeric(df["UTM_Northing"], errors="coerce")
df["21_Distance_from_obs"] = pd.to_numeric(df["21_Distance_from_obs"], errors="coerce")
df["22_Angle"] = pd.to_numeric(df["22_Angle"], errors="coerce")

# Convert angle to radians
df["angle_rad"] = np.deg2rad(df["22_Angle"])

# Calculate UTM offsets
df["delta_E"] = df["21_Distance_from_obs"]/1000 * np.sin(df["angle_rad"])
df["delta_N"] = df["21_Distance_from_obs"]/1000 * np.cos(df["angle_rad"])

# Projected UTM coordinates
df["proj_UTM_Easting"] = df["UTM_Easting"] + df["delta_E"]
df["proj_UTM_Northing"] = df["UTM_Northing"] + df["delta_N"]

# Fixing hemisphere logic
# Function to convert UTM Zone string like "42R" into EPSG code
def utm_zone_to_epsg(zone):
    number = int(zone[:-1])
    hemisphere = zone[-1].upper()
    return 32600 + number if hemisphere >= 'N' else 32700 + number
    
# Safe conversion function
def safe_convert_utm_to_latlon(row):
    try:
        epsg_code = utm_zone_to_epsg(row["UTM_Zone"])
        transformer = Transformer.from_crs(f"EPSG:{epsg_code}", "EPSG:4326", always_xy=True)
        lon, lat = transformer.transform(row["proj_UTM_Easting"], row["proj_UTM_Northing"])
        return pd.Series([lat, lon])
    except Exception as e:
        # You can log the error here if needed
        return pd.Series([None, None])

# Apply to DataFrame
df[["proj_latitude", "proj_longitude"]] = df.apply(safe_convert_utm_to_latlon, axis=1)

# Final projected location DataFrame
df_projected_locations = df[[
    "3_Date", "4_Start_Time", "5_Type_of_survey", "2_Name_of_the_person",
    "8_Species", "13_No_of_adult_males", "14_No_of_adult_femal",
    "15_No_of_immature_fe", "16_No_of_immature_ma", "17_No_of_unknown_age",
    "18_Notes", "20_Location", "21_Distance_from_obs", "22_Angle",
    "34_End_time","proj_latitude", "proj_longitude"
]]

# Ensure the '4_Start_Time' column is in datetime format
df_projected_locations["4_Start_Time"] = pd.to_datetime(df_projected_locations["4_Start_Time"], errors="coerce")

# Extract only the time part
df_projected_locations["4_Start_Time"] = df_projected_locations["4_Start_Time"].dt.time

# Optionally display or export
print(df_projected_locations.head())

      3_Date 4_Start_Time 5_Type_of_survey 2_Name_of_the_person 8_Species  \
0 2025-07-02     17:14:27          Vehicle         [Pradhyuman]       GIB
1 2025-07-01     17:05:44          Vehicle         [Pradhyuman]       NaN
2 2025-06-30     18:57:19          Vehicle         [Pradhyuman]       GIB
3 2025-06-30     07:11:28          Vehicle         [Pradhyuman]       GIB

   13_No_of_adult_males  14_No_of_adult_femal  15_No_of_immature_fe  \
0                   0.0                   1.0                   0.0
1                   NaN                   NaN                   NaN
2                   0.0                   1.0                   0.0
3                   1.0                   0.0                   0.0

   16_No_of_immature_ma  17_No_of_unknown_age 18_Notes  \
0                   1.0                   0.0
1                   NaN                   NaN      NaN
2                   1.0                   0.0
3                   0.0                   0.0

                                         20_Location  21_Distance_from_obs  \
0  {'latitude': 26.975388, 'longitude': 71.941547...                 180.0
1                                                NaN                   NaN
2  {'latitude': 26.97513, 'longitude': 71.93433, ...                 250.0
3  {'latitude': 27.008177, 'longitude': 71.986731...                 162.0

   22_Angle         34_End_time  proj_latitude  proj_longitude
0     190.0 2025-07-10 19:07:39      26.975386       71.941540
1       NaN 2025-07-10 19:09:43            NaN             NaN
2       NaN 2025-07-10 19:00:02            NaN             NaN
3     250.0 2025-07-10 08:13:33      27.008176       71.986729

C:\Users\campa\AppData\Local\Temp\ipykernel_12452\348654329.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_projected_locations["4_Start_Time"] = pd.to_datetime(df_projected_locations["4_Start_Time"], errors="coerce")
C:\Users\campa\AppData\Local\Temp\ipykernel_12452\348654329.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_projected_locations["4_Start_Time"] = df_projected_locations["4_Start_Time"].dt.time

In [29]:
df_projected_locations

,3_Date,4_Start_Time,5_Type_of_survey,2_Name_of_the_person,8_Species,13_No_of_adult_males,14_No_of_adult_femal,15_No_of_immature_fe,16_No_of_immature_ma,17_No_of_unknown_age,18_Notes,20_Location,21_Distance_from_obs,22_Angle,34_End_time,proj_latitude,proj_longitude
0,2025-07-02,17:14:27,Vehicle,[Pradhyuman],GIB,0.0,1.0,0.0,1.0,0.0,,"{'latitude': 26.975388, 'longitude': 71.941547...",180.0,190.0,2025-07-10 19:07:39,26.975386,71.941540
1,2025-07-01,17:05:44,Vehicle,[Pradhyuman],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-10 19:09:43,NaN,NaN
2,2025-06-30,18:57:19,Vehicle,[Pradhyuman],GIB,0.0,1.0,0.0,1.0,0.0,,"{'latitude': 26.97513, 'longitude': 71.93433, ...",250.0,NaN,2025-07-10 19:00:02,NaN,NaN
3,2025-06-30,07:11:28,Vehicle,[Pradhyuman],GIB,1.0,0.0,0.0,0.0,0.0,,"{'latitude': 27.008177, 'longitude': 71.986731...",162.0,250.0,2025-07-10 08:13:33,27.008176,71.986729

In [30]:
import simplekml

# Create a new KML object
kml = simplekml.Kml()

#df_projected_locations["proj_latitude"] = df_projected_locations["proj_latitude"].map(lambda x: f"{x:.5f} N")
#df_projected_locations["proj_longitude"] = df_projected_locations["proj_longitude"].map(lambda x: f"{x:.5f} E")
df_projected_locations["proj_latitude"].replace('', np.nan, inplace=True)
df_projected_locations["proj_longitude"].replace('', np.nan, inplace=True)
df_projected_locations = df_projected_locations.dropna(subset=['proj_latitude', 'proj_longitude'])
# Loop through each row in the projected location DataFrame
for _, row in df_projected_locations.iterrows():
    species = row["8_Species"]
    observer = row["2_Name_of_the_person"]
    date = row["3_Date"]
    lat = row["proj_latitude"]
    lon = row["proj_longitude"]
    
    # Add a placemark
    kml.newpoint(
        name=str(species),
        coords=[(lon, lat)],
        description=f"Observer: {observer}\nDate: {date}"
    )

# Save the KML file
kml.save("projected_sightings.kml")

C:\Users\campa\AppData\Local\Temp\ipykernel_12452\1081245973.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_projected_locations["proj_latitude"].replace('', np.nan, inplace=True)
C:\Users\campa\AppData\Local\Temp\ipykernel_12452\1081245973.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_projected_locations["proj_latitude"].replace('', np.nan, inplace=True)
C:\Users\campa\AppData\Local\Temp\ipykernel_12452\1081245973.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_projected_locations["proj_longitude"].replace('', np.nan, inplace=True)
C:\Users\campa\AppData\Local\Temp\ipykernel_12452\1081245973.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_projected_locations["proj_longitude"].replace('', np.nan, inplace=True)

In [31]:
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib

def send_email(send_to, subject, filename):
    send_from = "varunkher23@gmail.com"
    password = "zbooyeqgjolmhyyj"
    message1=f"Dear User, <br> <br> Please find the summarised data from GIB monitoring and nest search in Desert National Park WLS and Pokharan-Ramdeora-PFFR. \n                This is an automated mail.\n\n                Best Regards,\n                WII Bustard Recovery Program <br><br>"
    message2 = df_summary_html
    #message3 = f"<br>Habitat Sampling<br>"
    for receiver in send_to:
            multipart = MIMEMultipart()
            multipart["From"] = send_from
            multipart["To"] = receiver
            multipart["Subject"] = subject  
            filename = filename
            # Read a file and encode it into base64 format
            with open(filename,'rb') as file:
            # Attach the file with filename to the email
                multipart.attach(MIMEApplication(file.read(), Name='projected_sightings.kml'))
            multipart.attach(MIMEText(message1, "html"))
            multipart.attach(MIMEText(message2, "html"))
            #multipart.attach(MIMEText(message3, "html"))
            server = smtplib.SMTP("smtp.gmail.com", 587)
            server.starttls()
            server.login(multipart["From"], password)
            server.sendmail(multipart["From"], multipart["To"], multipart.as_string())
            server.quit()

In [32]:
send_email(["varunkher23@gmail.com"], "GIB monitoring summary", "projected_sightings.kml")